version: '3.7'

services:

    client:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        tty: true
        ports:
            - "3000:3000"
        volumes: 
            - ./frontend:/app
            - /app/node_modules
        networks:
            - frontend

    mongodb:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: "admin"
            MONGO_INITDB_ROOT_PASSWORD: "password"
            MONGO_INITDB_DATABASE: webapp
            MONGODB_DATA_DIR: /data/db
        volumes:
        - mongodbdata:/data/db
        networks:
        - backend
    
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: unless-stopped
        ports:
          - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
            ME_CONFIG_MONGODB_ADMINPASSWORD: "password"
            ME_CONFIG_MONGODB_SERVER: mongo
        networks:
        - backend

    api:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        command: python wsgi.py # --bind 0.0.0.0:5000 app:app
        ports:
            - "5000:5000"
        environment:
            FLASK_APP: "app"
            FLASK_ENV: "development"
            MONGODB_HOST: mongodb
            MONGODB_USERNAME: "apiuser"
            MONGODB_PASSWORD: "apipassword"
            HUBSPOT_CLIENT_ID: 9ed5b523-61a2-4b3a-9fbd-8d3bab84eee6
            HUBSPOT_CLIENT_SECRET: 1cf79138-396f-4e83-8fa5-62c10bd39264
        volumes:
            - appdata:/var/www/
            - ./backend/src:/app
        depends_on: 
            - mongodb
        networks:
            - frontend
            - backend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
volumes:
    mongodbdata:
        driver: local
    appdata:
        driver: local